name: Print hello.txt

on:
    push:
        branches:
            - main

jobs:
    print-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: read hello.txt
              run: |
                echo "---Reading hello.txt---"
                cat hello.txt
